CREATE OR REPLACE STREAM "DownStreamJ" (
    ID INTEGER,
    USERNAME VARCHAR(200),
    AMOUNT DECIMAL(5,2)
);
CREATE OR REPLACE STREAM "DownStreamK" (
    ID INTEGER,
    USERNAME VARCHAR(200),
    AMOUNT DECIMAL(5,2)
);
CREATE OR REPLACE STREAM "DownStreamL" (
    ID INTEGER,
    USERNAME VARCHAR(200),
    AMOUNT DECIMAL(5,2)
);

CREATE OR REPLACE PUMP "STREAM_PUMP1"
    AS INSERT INTO "DownStreamJ"
        SELECT STREAM ID, USERNAME, AMOUNT
        FROM "SOURCE_SQL_STREAM_001";

CREATE OR REPLACE PUMP "STREAM_PUMP2"
    AS INSERT INTO "DownStreamK"
        SELECT STREAM ID, USERNAME, AMOUNT
        FROM "SOURCE_SQL_STREAM_001";

CREATE OR REPLACE PUMP "STREAM_PUMP3"
    AS INSERT INTO "DownStreamL"
        SELECT STREAM ID, USERNAME, AMOUNT
        FROM "SOURCE_SQL_STREAM_001";
